### ISSUE TITLE
Error handling issues

### ISSUE THREAD

**Issue by pcrow** [dlenski/rsa_ct_kip#7]
I just tried this with an obsolete activation code, and the program exist with a Traceback instead of something more useful.  Buried in the text is the real message, so it's cosmetic, but it would be nice to clean it up.

```
Traceback (most recent call last):
  File ".local/bin/rsa_ct_kip", line 11, in <module>
    load_entry_point('rsa-ct-kip==0.4', 'console_scripts', 'rsa_ct_kip')()
  File "/home/me/.local/lib64/python3.6/site-packages/rsa_ct_kip/client.py", line 113, in main
    pd_res1, res1 = soap.parse_ServerResponse(raw_res1)
  File "/home/me/.local/lib64/python3.6/site-packages/rsa_ct_kip/client.py", line 64, in parse_ServerResponse
    raise RuntimeError(faultcode, faultstring)
RuntimeError: ('soapenv:Server.userException', 'java.rmi.RemoteException: The CT-KIP Web Service failed to process a client request. com.rsa.command.exception.InsufficientPrivilegeException: Invalid authorization code.; nested exception is: \n\tcom.rsa.command.exception.InsufficientPrivilegeException: Invalid authorization code.')
```

**Comment by dlenski** [comment]
Thanks, that's useful feedback. I didn't have any error handling because I know very little about the possible errors sent by the server. 

Even the part that's sent by the server is wrapper in several layers of Java exception-catching-and-logging crud:

```
java.rmi.RemoteException: The CT-KIP Web Service failed to process a client request. com.rsa.command.exception.InsufficientPrivilegeException: Invalid authorization code.; nested exception is: \n\tcom.rsa.command.exception.InsufficientPrivilegeException: Invalid authorization code.
```

I've improved things slightly by printing the bits that come from the server in a clearer fashion, and I'm going to add a special case for `Invalid authorization code` since it seems like it'll be a common one.

**Comment by pcrow** [comment]
Yup.  I figured you didn't have the opportunity to do negative testing to find and clean up the error handling, so I thought the error text would be useful.  It's my attempt to say "thank you" for making this available and doing what I can to make it even better for others.

**Comment by dlenski** [comment]
The RSA servers I used to have access to have been decommissioned, but I tested against the one referenced in [this document in Norwegian](https://www.haraldsplass.no/PublishingImages/om-haraldsplass/jobb-hos-oss/for-ansatte/2%20faktor%20brukerveiledning.pdf) and…

```
$ rsa_ct_kip https://rsa-ss.ihelse.net:443/ctkip/services/CtkipService INVALID_CODE
Sending ClientHello request to server...
Fault from server:
	java.rmi.RemoteException: The CT-KIP Web Service failed to process a client request. com.rsa.command.exception.InsufficientPrivilegeException: Invalid authorization code.; nested exception is: 
	com.rsa.command.exception.InsufficientPrivilegeException: Invalid authorization code.

Parsed exception:
	com.rsa.command.exception.InsufficientPrivilegeException: Invalid authorization code.
```

I think this result should be somewhat more explicable, and useful for future debugging as needed.

**Comment by pcrow** [comment]
Great!
