### ISSUE TITLE
How to serve the stdid to the RSA client?

### ISSUE THREAD

**Issue by m1t0s1s** [dlenski/rsa_ct_kip#8]
Hi, I saved the raw stdid file saved from a real RSA server, as well as the decoded one that stoken generates. Is there a way to serve it to the real RSA client via http? I saved it locally for work purposes but never really used it, but now I am regretting it (as others could see that I am not using the official RSA software client and it will invite questions from my manager).

Thanks in advance.

**Comment by dlenski** [comment]
> Is there a way to serve it to the real RSA client via http? I saved it locally for work purposes but never really used it, …

What is the "it" in these two sentences?

> as others could see that I am not using the official RSA software client and it will invite questions from my manager

In what way do you think they would be able to distinguish this? Both the official RSA client and `stoken` generate the same codes.

**Comment by dlenski** [comment]
***I basically don't understand at all what you're asking here, or what it has to do with this package***, but maybe this :point_down:  is the answer?

You can tell `stoken` to _export_ a token (e.g. `stoken export --android` to generate a URI like 
`http://127.0.0.1/securid/ctf?ctfData=245275959292847315163310727211013175046045533440312436504173141646133236671643734`, or `stoken export --sdtid`)…

… and then you can load that into the official RSA client, and thereby use the _same token_ with both `stoken` and the official RSA client.
