### ISSUE TITLE
No file saved after "WARNING: Token has already been committed on server, even though you did not save it."

### ISSUE THREAD

**Issue by alexvorobiev** [dlenski/rsa_ct_kip#9]
rsa_ct_kip connected to the server and seems to have received the data but then after printing "Token seed: XXX etc." showed that warning and did not create the sdtid file. There is also no ~/.stokenrc and no template file. The server says the token has been activated. Is there any way to restore the token from the seed or any other information it printed?

**Comment by dlenski** [comment]
You asked it _not_ to save the token, so that's what happened. Is anything unexpected here?

> Is there any way to restore the token from the seed or any other information it printed?

Yes. If you still have the seed, you can convert it into a working token. See the source code for how. https://github.com/dlenski/rsa_ct_kip/blob/master/rsa_ct_kip/client.py#L214-L234

**Comment by alexvorobiev** [comment]
Yes, that was what I ended up doing, all good now. It was my fault, I somehow missed that part of the documentation assuming that by default it will still create a file with some temporary name. Unfortunately the server decided that the token is now activated and refused subsequent calls.
